BoxLayout:
    orientation: 'vertical'
    Button:
        text: 'Clear'
    TextInput:
        id: input_name
        text: ''
        id: input_label
    Button:
        text: 'Don\'t click here'
        on_press: app.handle_boss()
        id: boss_label
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        id: output_label
    Label:
        text: 'Enter your name'
        id: input_name
        text: ''
        id: output_label
